### ISSUE TITLE
testing multiple factors

### ISSUE THREAD

**Issue by royfrancis** [PF2-pasteur-fr/SARTools#18]
In the example template, the code is designed for one factor with 2 to 4 levels.
~group (control, treatment)
but if I have more factors, say tissue or family, how do I do it?
~group+tissue+family
(control, treatment)
(a,b)
(1,2,3)

**Comment by hvaret** [comment]
SARTools can take into account one blocking factor (batch parameter) but not more since we can expect to have interactions between all the factors, and automating this task is difficult/dangerous. I prefer to let the user running directly DESeq2 or edgeR in this case. If you do not want to test for the interactions terms, you can add a column in the target file combining all your blocking factors.

Let me know if it is not clear!

Hugo

**Comment by royfrancis** [comment]
ok. thanks.
