### ISSUE TITLE
error when generating HTML files

### ISSUE THREAD

**Issue by mthernando** [PF2-pasteur-fr/SARTools#21]
Hi! I have a problem when running sartools. I have run sartools before and it did not happened! At the last part (generating HTML report) I obtain this error: 

```
> > # generating HTML report
> > writeReport.DESeq2(target=target, counts=counts, out.DESeq2=out.DESeq2, summaryResults=summaryResults,
> +                    majSequences=majSequences, workDir=workDir, projectName=projectName, author=author,
> +                    targetFile=targetFile, rawDir=rawDir, featuresToRemove=featuresToRemove, varInt=varInt,
> +                    condRef=condRef, batch=batch, fitType=fitType, cooksCutoff=cooksCutoff,
> +                    independentFiltering=independentFiltering, alpha=alpha, pAdjustMethod=pAdjustMethod,
> +                    typeTrans=typeTrans, locfunc=locfunc, colors=colors)
> Quitting from lines 63-100 (/home/azken/R/x86_64-pc-linux-gnu-library/3.3/SARTools/report_DESeq2.rmd) 
> Error in eval(expr, envir, enclos) : objeto 'nbNull' no encontrado
```

I would appreciate your help. Best regards,

Maria

**Comment by hvaret** [comment]
Dear Maria,

thank you very much for reporting this problem. Some colleagues already obtained this error message but I can't understand what happened because all went good when they re-ran SARTools with me.

Could you try to run the script again and tell me if you still have the error?

Best regards,

Hugo

**Comment by mthernando** [comment]
Dear Hugo, I have re-run the script in R environment (not Rstudio) and I find the same error: 

```
Quitting from lines 63-100 (/home/azken/R/x86_64-pc-linux-gnu-library/3.3/SARTools/report_DESeq2.rmd) 
Error in eval(expr, envir, enclos) : objeto 'nbNull' no encontrado
Además: Warning message:
In descriptionPlots(counts = counts, group = target[, varInt], col = colors) :
  No pairwise scatter-plot produced because of a too high number of samples (>30).
```

**Comment by hvaret** [comment]
OK thank you for having re-run the script. If your data are not confidential, could you send me the target and count files at hugo.varet at pasteur.fr ? I will reproduce the bug and then try to fix it.

Hugo

**Comment by mthernando** [comment]
sent!

**Comment by fabiansan** [comment]
I just got the same error and for asking would the reason could be I just created my github profile. Interestingly, everything run smoothly after I deleted every output which was generated before. So kind of a "restart" of the script helped in my case.

**Comment by hvaret** [comment]
Thanks @fabiansan for your message! It is very strange because one line of code seems to be skipped when generating the HTML report (`nbNull <- nrow(counts) - nrow(removeNull(counts))`, see the [rmd file](https://github.com/PF2-pasteur-fr/SARTools/blob/master/inst/report_DESeq2.rmd) containing the skeleton of the report.
