### ISSUE TITLE
SARtools useable for experimental setup with both time and concentration

### ISSUE THREAD

**Issue by TokeB-A** [PF2-pasteur-fr/SARTools#29]
Thank you for developing SARtools!

As far as I can read SARtools can not be used on my data due to the experiemtal setup. But I want to be absolutely sure before excluding SARtools as a way to smoothly analyze my data.

I have RNA-seq data (gene counts) from an experiment where we look into changes in gene counts after addition of different concentration of a compound and over time.
So we have Concentrations: 0, 3, 12, 90 and Times: 0, 3, 30 and 100 days.

So we need to now which (if) gene counts significantly change ( in comparison to concentration 0, time 0 = control) with the different concentrations added and with time.

Maybe this can be tested looking at times seperately and then look at changes in genes with different wood ash concentrations? And the same for time: Looking at concentrations seperately and then look at changes in genes with different times

Any advice on this? Do you advice to use SARtools for this?

Hope the descriptions makes sense.

Thank you very much in advance!

**Comment by hvaret** [comment]
Hi TokeB-A,

thanks for your message! If I understand correctly, you want to study simultaneously two factors (time and concentration) and their interaction. With SARTools, a solution would be to create a new variable in the target file concatenating the time and concentration variables. SARTools will then perform each pairwise comparison but some of them won't be relevant as both time and concentration will change.

I thus think it will be easier to use either DESeq2 or edgeR directly in order to fit a GLM and test for the the comparisons you are interested in (defining the correct contrasts).

Hope this helps!

Best,

Hugo

**Comment by TokeB-A** [comment]
Thank you Hugo! Makes sense.
