### ISSUE TITLE
RSEM file format

### ISSUE THREAD

**Issue by Cdk29** [PF2-pasteur-fr/SARTools#33]
Hi.

I did wanted to use the executable template for DESeq2 "template_script_DESeq2_CL.r" on RNA-seq data from a TGCA cohort. The files are in RSEM count, and I get the following :

Error in loadCountData(target = target, rawDir = rawDir, featuresToRemove = featuresToRemove) : 
  Input counts are not integer values as required by DESeq2 and edgeR.

Or the maintenor of the package DESeq2 tell himself that this format is supported by the DESeq2 library here https://support.bioconductor.org/p/91054/ , and there is a pipeline to pass RSEM file to DESeq2 as shown here : https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html

Is there a way to override this warning ? (which stop the script)

**Comment by hvaret** [comment]
Hi @Cdk29,

thanks for your suggestion. Actually DESeq2 and edgeR were expecting counts (integer values) as input when I started developing SARTools, these counts are typically generated by HTSeq-count or featureCounts to perform an analysis at the gene level. RSEM is often used to quantify the expression at the isoform/transcript level, and tximport is a very nice package to link RSEM outputs to DESeq2. 

I agree that integrating tximport to SARTools could be a nice feature as salmon, sailfish, kallisto and RSEM outputs could then be passed to SARTools. However I consider it is a more advanced kind of analysis and I would recommend to use directly tximport+DESeq2 instead of tximport+SARTools.

Thanks again,

Hugo

**Comment by Cdk29** [comment]
Hi !

Thanks for the reply. Does tximport modify the counts somehow ? Or I can just comment the exit of the script and run sartools on the RNA-seq files in RSEM format ?

**Comment by Cdk29** [comment]
Hi !

Thanks for the quick reply. Does tximport modify the counts somehow ? As far as I understand it is just about reframing the data input. Can I just comment the exit of the script and run sartools on the RNA-seq files in RSEM count ? (format file : CSV)

**Comment by hvaret** [comment]
Hi,
I do not remember exactly what tximport does, I only remember that there are several options to import the data (e.g. countsFromAbundance parameter in tximport() function). You can try to import RSEM files and then pass the matrix to SARTools modifying the R script, but make sure that the samples/columns are correctly ordered and named according to the target design file.
Best,
Hugo
