### ISSUE TITLE
plot labels by batch, not sample name, then rely on colour to determine specific sample (condition)

### ISSUE THREAD

**Issue by vmkalbskopf** [PF2-pasteur-fr/SARTools#74]
Hi there
My samples are named by condition+batch, but even though the names are quite short, only 4 or 5 letters, the plots get quite messy.
I'd also like to have simpler, cleaner axis labels without repeating condition info, which I can represent with an annotation. 

As an example, I have two conditions, Day 1 and Day 2, and 10 bio-replicates, 1-10. So my samples are named D1B1, D2B1, ........... D1B5, D2B5...  etc.
So if I could label the samples in the PCA plot, for example B1 and B2 only, then rely on colour to distinguish condition, the plot will be much cleaner. And same for the x-axis sample labels in the "Total read count per sample" plot. 

Would this be difficult to do? 

P.S.
I found that I can't simply edit the plot afterwards, even if it an EPS file, as removing characters makes changes to the placement of the text.

**Comment by hvaret** [comment]
Hi,
I understand your suggestion but it is very important for SARTools to have unique sample names and I prefer using them rather than adding a label not necessarily unique. Moreover the names on the PCA are placed such that they do not overlap so if your sample names have only 4 or 5 letters the plot should look nice.
Hugo
