### ISSUE TITLE
Gene lenght corrected value

### ISSUE THREAD

**Issue by Bury-Mone** [PF2-pasteur-fr/SARTools#80]
Hi, I love using SARTools. I wonder if it is possible to use it with the GeTMM (Gene leght corrected trimmed mean of M-values) function, that allows both intersample and intrasample comparison (see: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2246-7). If yes, could you tell me the code I should use in my script to choose this option. What do you think about the possibility of dividing the counts normalized by DEseq2 by the gene size to make intrasample gene expression comparisons. I thank you by advance for your help. All the best.

**Comment by hvaret** [comment]
Hi,
thanks a lot for your suggestion. I did not plan to add any new normalization strategy in the future and I prefer to let only the default methods, especially because SARTools is designed to use the default DESeq2/edgeR "pipeline". Unfortunately I did not know this paper and I am not familiar with intra-sample comparisons so I can't tell you any feedback about GeTMM.
Best,
Hugo
